blog:
  title: 'tuRBo'
  subtitle: 'the ultimate ruby blog :O'
  url: &url "https://example.com"
  version: 0.7.1 beta
social:
  rss: 
    - *url
    - /feed?format=rss
  github: https://github.com/<nick>
  steam: https://steamcommunity.com/id/<nick>
  flickr: https://flickr.com/photos/<nick>
  mail: mailto:mail@example.com
