blog:
  title: 'tuRBo'
  subtitle: 'the ultimate ruby blog :O'
  url: &url "https://example.com"
  version: '0.9.7b (Bootstrap v4 Alpha)'
layout:
  admin: 'admin-bootstrap4'
social:
  rss: 
    - *url
    - /feed?format=rss
  github: https://github.com/<nick>
  steam: https://steamcommunity.com/id/<nick>
  flickr: https://flickr.com/photos/<nick>
  mail: mailto:mail@example.com
recaptcha:
  pubkey: 6Lc6BAAAAAAAAChqRbQZcn_yyyyyyyyyyyyyyyyy
  privkey: 6Lc6BAAAAAAAAKN3DRm6VA_xxxxxxxxxxxxxxxxx
